### ISSUE TITLE
Brouter backend docker container

### ISSUE THREAD

**Issue by bvarick** [bvarick/route_analysis#11]
I changed the `docker` directory to include two subdirectories: `osrm` and `brouter`. 

And I added to the make file:
- `make brouter-data` which clones the git directories for brouter and brouter-web, downloads the relevant data, adjusts config files, and builds the docker images.
- `make brouter-container` which starts the brouter containers. 
 
Then the front-end (`brouter-web`) should be available on [http://127.0.0.1:8080](http://127.0.0.1:8080) and the backend (`brouter`) at `http://127.0.0.1:17777/brouter`

I renamed the previous make commands for osrm to:
- `make osrm-data`: preprocesses the osrm data
- `make osrm-container`: starts the osrm containers

The RMarkdown file `cycling_route_analysis_brouter.Rmd` needs both the brouter backend (for routes) and osrm backend (for the isodistance polygon)

**Comment by syounkin** [comment]
This is running without error on my machine.
